In [1]:
!pip install numpy

In [2]:
# Create a 3x3 matrix with values ranging from 0 to 8:
import numpy as np
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
# Reverse the rows of the matrix created in Exercise 1:
reversed_matrix = np.flipud(matrix)
print(reversed_matrix)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [4]:
# Find the mean, median, and standard deviation of the matrix:
mean_value = np.mean(matrix)
median_value = np.median(matrix)
std_deviation = np.std(matrix)
print("Mean:", mean_value, "Median:", median_value, "Standard Deviation:", std_deviation)

Mean: 4.0 Median: 4.0 Standard Deviation: 2.581988897471611


In [5]:
# Normalize the values in the matrix (subtract mean and divide by standard deviation):
normalized_matrix = (matrix - mean_value) / std_deviation
print(normalized_matrix)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [6]:
# Extract all odd numbers from the matrix:
odd_numbers = matrix[matrix % 2 != 0]
print(odd_numbers)

[1 3 5 7]


In [ ]:
# Replace all even numbers in the matrix with -1:
matrix[matrix % 2 == 0] = -1
print(matrix)

In [ ]:
#Perform matrix multiplication between a 3x2 matrix and a 2x4 matrix:
matrix_a = np.random.random((3, 2))
matrix_b = np.random.random((2, 4))
result_matrix = np.dot(matrix_a, matrix_b)
print(result_matrix)

In [ ]:
#Reshape a 1D array to a 2D array with 4 rows and 3 columns:
original_array = np.arange(12)
reshaped_array = original_array.reshape(4, 3)
print(reshaped_array)

In [ ]:
#Stack two arrays vertically:
array1 = np.ones((3, 4))
array2 = np.zeros((3, 4))
stacked_array = np.vstack((array1, array2))
print(stacked_array)

In [ ]:
#Calculate the dot product of two vectors:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
dot_product = np.dot(vector1, vector2)
print(dot_product)